version: '3.8'
services:
  pega-postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: pega-postgres
    image: pega-postgres:latest
    env_file: '.env'
    restart: unless-stopped
    networks:
    - pega
    ports:
    - 5434:5432
    volumes:
     - ./postgres-data:/var/lib/postgresql/data
#   - .:/src
#    - .env.prod:/src/.env
  pega-installer:
    build:
      context: .
      dockerfile: Dockerfile.install
    container_name: pega-installer
    image: pega-installer:latest
    depends_on:
      - pega-postgres
    env_file: '.env'
#    restart: unless-stopped
    networks:
    - pega  

  pega-web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: pega-web
    image: pega-web:latest
    env_file: '.env'
    depends_on:
      - pega-installer
    restart: unless-stopped
    ports:
    - 8080:8080
    networks:
    - pega


  pg-admin:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    container_name: pg-admin
    image: pg-admin4:latest
    env_file: '.env'
    depends_on:
      - pega-postgres
    restart: unless-stopped
    ports:
    - 8081:80
    networks:
    - pega


networks:
  pega:
    name: pega-network
